### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [ContextMapper/context-mapper-dsl#195]
Hello Context Mapper DSL team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the Context Mapper DSL project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by stefan-ka** [comment]
Hi @miklossy,

thanks for getting in touch with us!
Of course, would be nice to be listed on your page... I suggest to add Context Mapper as follows:

```html
<tr>
	<td><a href="https://contextmapper.org">Context Mapper</a></td>
	<td>ContextMapper is an open source framework providing a Domain-specific Language (DSL) for strategic and tactic Domain-driven Design (DDD). It supports bounded context mapping, service decomposition, and PlantUML model generation. The framework components allow software architects and microservice designers to reverse engineers Context Maps from Spring Boot and Docker Compose files, to improve the architecture iteratively, and to convert models into other representations.</td>
	<td>Apache 2.0 License</td>
	<td>Language, Modeling Framework</td>
	<td><a href="https://stefan.kapferer.ch/">Stefan Kapferer</a>, <a href="https://www.ifs.hsr.ch/Olaf-Zimmermann.11623.0.html?&amp;L=4">Olaf Zimmermann</a></td>
</tr>
```

I hope that's fine, otherwise let me know.

Thanks again and best regards,
Stefan

**Comment by miklossy** [comment]
Thank you @stefan-ka !

**Comment by miklossy** [comment]
The `Context Mapper` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by stefan-ka** [comment]
Thanks @miklossy!

**Comment by stefan-ka** [comment]
@miklossy, seems like we have been removed again, right.?

![image](https://user-images.githubusercontent.com/6763278/80083139-8e0aac80-8555-11ea-8d75-f219c1e0e422.png)

**Comment by miklossy** [comment]
@stefan-ka on my computer is the `Context Mapper DSL` project is still there:
![screenshot](https://user-images.githubusercontent.com/20393472/80083669-2acd4a00-8556-11ea-9ef4-205c3e4a4ee1.png)
However, we experienced some problem with different Eclipse servers in the past.
@cdietrich: Is the project visible for you?

**Comment by cdietrich** [comment]
i dont see it @miklossy CRtl+F5 ?

**Comment by miklossy** [comment]
After hitting `CTRL+F5` the project is still visible. It is also listed on the [website-publish](https://github.com/eclipse/xtext/blob/68b7d66f1518c51b0019dec97047465cdd2be08f/xtext-website/community.html#L238-L244) branch

**Comment by stefan-ka** [comment]
I tried `CTRL+F5` several times, different browsers, different networks... Don't see it anywhere.

**Comment by cdietrich** [comment]
bug in eclipse webservers?

**Comment by cdietrich** [comment]
i see it sometimes and sometimes not

**Comment by miklossy** [comment]
Let's keep observing it.

**Comment by miklossy** [comment]
The `Context Mapper` project is still visible on my computer. 
@cdietrich @stefan-ka Can you also see it?

**Comment by cdietrich** [comment]
yes it is there

**Comment by stefan-ka** [comment]
Nope, I can still not see it @miklossy. `CTRL+F5` does not help (also tried on different devices).
Maybe multiple servers or load balancers with invalid caches?

**Comment by cdietrich** [comment]
@miklossy  can you please open a bugzilla for webmasters to investigate

**Comment by miklossy** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562518

**Comment by cdietrich** [comment]
@stefan-ka the eclipse webmasters have fixed "something". can you please retry

**Comment by stefan-ka** [comment]
Looks good, @cdietrich!
