### ISSUE TITLE
Team map generation

### ISSUE THREAD

**Issue by seb4stien** [ContextMapper/context-mapper-dsl#241]
Hi. The contextmapper tools is really interesting. I am struggling a bit with the visualstudio code extension to generate anything else from contextmap.
How should I proceed to generate this kind of output: https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/insurance-example/images/TeamMap-Illustration.png is it supported by the extension?

**Comment by seb4stien** [comment]
It's indeed a duplicate of https://github.com/ContextMapper/context-map-generator/issues/5 
It could be worth adding a comment in the documentation that this one is manually generated ;)

**Comment by stefan-ka** [comment]
Okay, thanks @seb4stien. Since we heard the requirement more than once now, we should consider implementing https://github.com/ContextMapper/context-map-generator/issues/5 :)
