### ISSUE TITLE
FileSystemHelper isn't included in library?

### ISSUE THREAD

**Issue by Syseat** [ContextMapper/context-mapper-dsl#243]
I included the library in my project via gradle with:
`implementation 'org.contextmapper:context-mapper-dsl:5.15.0'`

My goal is to generate PlantUML files from a cml-File. Therefor I tried it like the provided [code example](https://github.com/ContextMapper/context-mapper-standalone-example/blob/master/src/main/java/org/contextmapper/standalone/example/MDSLGeneratorExample.java).

But the FileSystemHelper can't be found in the library.
Is there somthing I am missing?

**Comment by stefan-ka** [comment]
Hi @Syseat 

With Context Mapper [v6.0.0](https://contextmapper.org/news/2020/09/23/v6.0.0-released/) (released today) we improved the API for standalone usage. You don't have to copy the `FileSystemHelper` anymore.

Checkout how to use Context Mapper standalone in the [release notes](https://contextmapper.org/news/2020/09/23/v6.0.0-released/#standalone-api-improvements) (just a few simple examples) or directly in our standalone example project: https://github.com/ContextMapper/context-mapper-standalone-example (I adjusted all examples to the new API).

I hope this solves the issue for you. I.e. generating PlantUML diagrams is [quite simple now](https://github.com/ContextMapper/context-mapper-standalone-example/blob/master/src/main/java/org/contextmapper/standalone/example/PlantUMLGeneratorExample.java):

```java
public class PlantUMLGeneratorExample {
    public static void main(String[] args) {
        StandaloneContextMapperAPI contextMapper = ContextMapperStandaloneSetup.getStandaloneAPI();
        CMLResource resource = contextMapper.loadCML(INSURANCE_EXAMPLE_URI);

        contextMapper.callGenerator(resource, new PlantUMLGenerator());
    }
}
```

Best regards,
Stefan
