### ISSUE TITLE
Generate a UML use case diagram for/from Use Cases/User Stories

### ISSUE THREAD

**Issue by socadk** [ContextMapper/context-mapper-dsl#291]
... to support documentation-as-code even further. https://plantuml.com/use-case-diagram

**Comment by stefan-ka** [comment]
@socadk 

I implemented a first, very simplistic, implementation that generates a use case diagram based on our use cases (or user stories) and its actors:

![image](https://user-images.githubusercontent.com/6763278/235073773-dfe8835f-4ea4-457c-a065-900437023352.png)

What do you think?

**Comment by socadk** [comment]
Off to a good start!
