### ISSUE TITLE
"Open Flow in Sketch Miner" quick fix broken

### ISSUE THREAD

**Issue by socadk** [ContextMapper/context-mapper-dsl#293]
While the .sketch-miner files are generated successfully, the direct route to the browser display no longer works: Sketch Miner opens but shows its default model and URI.  Problem occurs on Windows, both VSC and Eclipse. Since 6.4 (I believe).

**Comment by socadk** [comment]
Might be a problem in https://www.bpmn-sketch-miner.ai/index.html#

**Comment by stefan-ka** [comment]
This issues is fixed with the bugfix release v6.5.1: https://github.com/ContextMapper/context-mapper-dsl/releases/tag/v6.5.1

Works again on Windows (VS Code as well as Eclipse).
