### ISSUE TITLE
Initial Build and eclipse import results in missing plug-ins

### ISSUE THREAD

**Issue by JuergenMutschall** [ContextMapper/context-mapper-dsl#294]
After following the steps on page
https://github.com/ContextMapper/context-mapper-dsl/wiki/Build
and
https://github.com/ContextMapper/context-mapper-dsl/wiki/IDE-Setup

there are still a lot of plugins missing in the setup of the eclipse projects (allthough the jars are contained in the repository project):

Missing bundles in org.contextmapper.dsl:
org.eclipse.emf.henshin.interpreter;bundle-version="1.4.0",
 org.contextmapper.contextmap.generator;bundle-version="1.2.1",
 org.apache.commons.lang3;bundle-version="3.9.0",
 org.apache.commons.exec;bundle-version="1.3.0",
 guru.nidi.com.kitfox.svgSalamander;bundle-version="1.1.2",
 org.contextmapper.servicecutter.library;bundle-version="1.2.1",
 org.freemarker.freemarker;bundle-version="2.3.30",
 com.fasterxml.jackson.core.jackson-annotations,
 com.fasterxml.jackson.core.jackson-core,
 com.fasterxml.jackson.core.jackson-databind,
 org.yaml.snakeyaml;bundle-version="1.14.0",
 org.nlpub.watset;bundle-version="2.1.5",
 org.jgrapht.core;bundle-version="1.4.0",
 org.apache.commons.math3;bundle-version="3.6.1"

Missing bundles in org.contextmapper.dsl.ide:
org.apache.commons.lang3;bundle-version="3.9.0"

Missing bundles in org.contextmapper.dsl.ide.tests:
org.contextmapper.contextmap.generator;bundle-version="1.2.1",
 org.contextmapper.servicecutter.library;bundle-version="1.2.1",
 org.graphstream.gs-core;bundle-version="1.3.0",
 org.graphstream.gs-algo;bundle-version="1.3.0",

Missing bundles in org.contextmapper.dsl.tests:
org.contextmapper.contextmap.generator;bundle-version="1.2.1",
 org.contextmapper.servicecutter.library;bundle-version="1.2.1",
 org.graphstream.gs-core;bundle-version="1.3.0",
 org.graphstream.gs-algo;bundle-version="1.3.0",

Missing bundles in org.contextmapper.dsl.ui:
org.contextmapper.servicecutter.library

Context/Platform:
OS: Ubuntu 20.04 in WSL2
latest download of  eclipse
maven build succeeded
integration test succeeded
no errors in creating the infrastructure in eclipse

**Comment by stefan-ka** [comment]
Hi @JuergenMutschall 

Yeah, always funny with Eclipse initially. You probably have to open the target definition file (`context-mapper-dsl/org.contextmapper.dsl.target/org.contextmapper.dsl.target.target`) and click `Set as target platform`. 

![image](https://user-images.githubusercontent.com/6763278/120112575-b01e2780-c176-11eb-93ae-39235ec3a92d.png)

And after that you probably have make a "Clean Build" again... I should add this as a hint in the README.

Best regards,
Stefan

**Comment by JuergenMutschall** [comment]
Hi,

context-mapper-dsl/org.contextmapper.dsl.target/org.contextmapper.dsl.target.target did not work for me. 

But

context-mapper-dsl.**parent**/org.contextmapper.dsl.target/org.contextmapper.dsl.target.target did it.

Thank you

Juergen
