### ISSUE TITLE
Eclipse Plugin cant be installed due to osgi.bundle missing

### ISSUE THREAD

**Issue by rondu-dev** [ContextMapper/context-mapper-dsl#300]
When installing via Eclipse Market Place i get the following error on the installation.
annot complete the install because one or more required items could not be found.
  Software being installed: Context Mapper DSL Editor 6.5.1 (org.contextmapper.dsl.feature.feature.group 6.5.1)
  Missing requirement: Henshin Diagram Editor Plugin 1.6.0.202001052147 (org.eclipse.emf.henshin.diagram 1.6.0.202001052147) requires 'osgi.bundle; org.eclipse.papyrus.infra.gmfdiag.tooling.runtime 0.0.0' but it could not be found
  Missing requirement: Henshin Diagram Editor Plugin 1.6.0.202002251401 (org.eclipse.emf.henshin.diagram 1.6.0.202002251401) requires 'osgi.bundle; org.eclipse.papyrus.infra.gmfdiag.tooling.runtime 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: org.contextmapper.dsl 6.5.1 (org.contextmapper.dsl 6.5.1)
    To: osgi.bundle; org.eclipse.emf.henshin.interpreter 1.4.0
  Cannot satisfy dependency:
    From: Context Mapper DSL Editor 6.5.1 (org.contextmapper.dsl.feature.feature.group 6.5.1)
    To: org.eclipse.equinox.p2.iu; org.contextmapper.dsl [6.5.1,6.5.1]
  Cannot satisfy dependency:
    From: Henshin Interpreter 1.6.0.202001052147 (org.eclipse.emf.henshin.interpreter 1.6.0.202001052147)
    To: java.package; org.eclipse.emf.henshin.diagram.providers 0.0.0
  Cannot satisfy dependency:
    From: Henshin Interpreter 1.6.0.202002251401 (org.eclipse.emf.henshin.interpreter 1.6.0.202002251401)
    To: java.package; org.eclipse.emf.henshin.diagram.providers 0.0.0

**Comment by stefan-ka** [comment]
Hi @rondu-dev 

We published a bugfix release (v6.5.2) today. It is now possible to install Context Mapper in Eclipse 2021-06.

Therefore I close this issue... Maybe you can also check if it works for you and let us know if you experience any problems.

Thanks again for reporting!
Stefan
