### ISSUE TITLE
Error when creating a list of Enums

### ISSUE THREAD

**Issue by juan-conca** [ContextMapper/context-mapper-dsl#325]
**Describe the bug**
When I define a ValueObject that contains a reference to a List<MyEnum>, complains about the attribute and fails.

**To Reproduce**
Create your own Enum in the model:

```cml
        enum Roles {
            ENUM_1,
            ENUM_2,
            ENUM_3,
            ENUM_4
        }
```

Then in your ValueObject, make a reference to a list of them:

```cml
        ValueObject User {
            - List<Roles> roles;
        }
```

And when compile, then an error appears complaining about the line: ` - List<Roles> roles;`

**Expected behaviour**
I suppose that this must be accepted and usable in case of user with several roles, or an object with a list of accepted states to move, etc.

**IDE and Plugin (please complete the following information):**
 - IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation

Non-Bundled Plugins:
    com.intellij.kubernetes (223.7571.188)
    com.dubreuia (2.3.0)
    de.docksnet.puml.syntaxchecker (0.2.0)
    PlantUML integration (5.20)
    org.asciidoctor.intellij.asciidoc (0.38.3)
    org.mapstruct.intellij (1.4.0)
    com.haulmont.jpab (2022.5.1-223)
    org.sonarlint.idea (7.2.1.58118)

Kotlin: 223-1.7.20-release-201-IJ7571.182
 - ContextMapper plugin version

**Additional context**

**Comment by stefan-ka** [comment]
Thank you very much for reporting @juan-conca!

**Comment by stefan-ka** [comment]
I agree, we should allow this. The grammar is not the problem, but there is an explicit Sculptor validator that does not allow this; don't actually know why or what the thoughts were there. I think we can adjust this, but we have to check that all the generators can handle it.

**Comment by stefan-ka** [comment]
Fixed this one. Will be released with our next version in May.
