### ISSUE TITLE
Service or Domain Service should be at same level as Aggregate and not within aggregate

### ISSUE THREAD

**Issue by sandeepjagtap** [ContextMapper/context-mapper-dsl#326]
My understanding is Domain Service and Aggregates are siblings. As per blue book sometimes it is not a thing and more of business process which should then be modelled as "Domain Service" e.g. FundTransfer Domain Service which debits one Account Entity and credits another Account Entity.

So following documentation says - we need to specify service within Aggregate. I would assume domain service should be able to specified instead of Aggregate and not within Aggregate?

From https://contextmapper.org/docs/tactic-ddd/ documentation -
---------------
Services
Within your aggregate you can also specify services according to the tactic DDD Service pattern. Services are declared with the Service keyword and contain one or more methods/operations. These methods/operations are declared exactly the same way as within entities, value objects or domain events, but without the def keyword:

Service RoutingService {
  List<@Itinerary> fetchRoutesForSpecification(@RouteSpecification routeSpecification) throws LocationNotFoundException;
}
-----------------

**Comment by stefan-ka** [comment]
Hi @sandeepjagtap 

Thanks for creating the issue!

I absolutely agree that we should refactor this. We inherited the structure originally vom Sculptor DSL.

We'll have to see when or how we could such a change, as it is a breaking change in the CML grammar. Maybe we can also check whether we could support both (old and new/correct).

Best regards,
Stefan

**Comment by stefan-ka** [comment]
Done. Will be published with next release in May.

To be backwards compatible, both will be possible now (Services inside Aggregates as before; and Services on the same level as Aggregates).
