### ISSUE TITLE
Error message when not being able to generate puml

### ISSUE THREAD

**Issue by socadk** [ContextMapper/context-mapper-dsl#340]
**Describe the bug**
I modelled a domain with a subdomain. No entities or other elements in subdomain yet. When I try to generate PlantUML, the error message informs me:

> Error occurred: Your model does not contain a Context Map, a Bounded Context, a Subdomain, or Use Cases or User Stories. Therefore we have nothing to generate. Create at least one of the mentioned Objects.

which is not 100% correct. I can see why nothing is generated, but error message could be more accurate.

**Comment by stefan-ka** [comment]
Fixed with v6.9.0.
