### ISSUE TITLE
char to hex conversion breaking in VScode ContextMapper plugin...

### ISSUE THREAD

**Issue by sharvar** [ContextMapper/context-mapper-dsl#345]
**About the bug**
Getting below error when trying to cut services using 'Propose New Service Cut' in VScode using contextMapper extension. 

"Error occurred: The project directory '\\c%3A\Users\149874\Downloads\service_cutter' does not exist!"

Actual path from where .cml file is opened in VScode is mentioned below. Looks like ContexMapper converts between char and hex and it is breaking in between.
c:\Users\149874\Downloads\service_cutter\
All other commands like - 'Generate Service Cutter Input' are working except 'Propose New Service Cut'

**To Reproduce**
1. Open a .cml file in VScode
2. Right click on it
3. Click on 'Propose New Service Cut'

**Expected behavior**
.cml file should have proposed services...

**Input files to reproduce**
https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/insurance-example/Insurance-Example-Stage-1.cml

**IDE and Plugin (please complete the following information):**
 - VSCode version - 1.79.2
 - ContextMapper plugin version - v6.8.0

**Comment by stefan-ka** [comment]
Unfortunately we had to disable the Service Cutter integration in Context Mapper for now: https://contextmapper.org/news/2023/11/24/v6.10.0-released/

I'll close this one for now, as we have to re-test all Service Cutter features anyway - in case we re-integrate it.
