### ISSUE TITLE
Command line mechanism to generate plantuml files

### ISSUE THREAD

**Issue by kmanikandan-kmk** [ContextMapper/context-mapper-dsl#83]
Hi,

I have been going through docs and trying your examples to explore the possibility of using "Domain Driven Design" in our team. The examples are good and they work easily with Eclipse IDE.

It would be helpful if there is a command line way to generate plantuml files other than running Eclipse plug-in.

Please let me know if there is a command line way to generate plantuml files.

Regards
KMK
K.Manikandan

**Comment by stefan-ka** [comment]
Hi @kmanikandan-kmk 

We haven't implemented a CLI yet, but the language including its tools (generators, etc.) are now available as standalone library in the [Maven central](https://search.maven.org/search?q=g:%22org.contextmapper%22%20AND%20a:%22context-mapper-dsl%22). With the standalone library it is now possible to use the language and the generators outside Eclipse.

In our [standalone example project](https://github.com/ContextMapper/context-mapper-standalone-example) you find a Java class [PlantUMLGeneratorExample](https://github.com/ContextMapper/context-mapper-standalone-example/blob/master/src/main/java/org/contextmapper/standalone/example/PlantUMLGeneratorExample.java) showing how you can simply generate the PlantUML diagrams out of your CML model with a few lines of code:

```java
public class PlantUMLGeneratorExample {

	public final static String INSURANCE_EXAMPLE_URI = "./src/main/cml/Insurance-Example-Model.cml";

	public static void main(String[] args) {
		// Setup and loading CML file:
		ContextMappingDSLStandaloneSetup.doSetup();
		Resource resource = new ResourceSetImpl().getResource(URI.createURI(INSURANCE_EXAMPLE_URI), true);
		
		// Create the PlantUML generator
		PlantUMLGenerator generator = new PlantUMLGenerator();
		
		// Generate the diagrams into 'src-gen'
		JavaIoFileSystemAccess javaIoFileSystemAccess = FileSystemHelper.getFileSystemAccess();
		javaIoFileSystemAccess.setOutputPath("./src-gen");
		generator.doGenerate(resource, javaIoFileSystemAccess, new GeneratorContext());
	}
}
```
Maybe this could already help, if you are still interested in using the tool... You could write a Java program as shown above (maybe take input-file URI and output-directory as parameter), build an executable JAR, and call it from the command line. 

We hope to provide a CLI tool in the future, but this takes more time and is not our first priority right now.

**Comment by stefan-ka** [comment]
@kmanikandan-kmk, you can find a first very simple approach towards a CLI here:
https://github.com/ContextMapper/context-mapper-standalone-example#cli

Still calling java directly but already quite comfortable...

**Comment by stefan-ka** [comment]
@kmanikandan-kmk, there is an official CLI now, you can find everything here: https://github.com/ContextMapper/context-mapper-cli
Best regards, Stefan
